# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Flashy Tableviews' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Flashy Tableviews

  pod 'SWTableViewCell', '~> 0.3.7'
  pod 'APParallaxHeader'

  target 'Flashy TableviewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Flashy TableviewsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
